version: '3.7'

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
        MYSQL_DATABASE: 'mysite'
        MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3307:3306"
    container_name: mysql 

      
  web:
    restart: always
    image: web
    build: ./
    volumes:
      - ./:/code
    ports:
      - "8002:8000"
    links:
      - mysql
    networks:
      - django-mysql-docker_default
    depends_on:
      - mysql

networks:
  django-mysql-docker_default:
    external: true

