version: '2'

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
        MYSQL_DATABASE: 'mysite'
        MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3307:3306"
    container_name: mysql 

      
  web:
    restart: always
    image: web
    build: ./
    volumes:
      - ./:/code
    ports:
      - "8010:8000"
    links:
      - mysql
